spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/contentaura
        username: postgres
        password: diya555
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    batch_size: 30
                order_insertes: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    task:
      execution:
        pool:
            core-size: 2
            max-size: 5
            queue-capacity: 500

server:
    port: 8081
