spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contentaura
    username: postgres
    password: diya555
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    node:
      schema:
        validation:
          url=http://localhost:3001/validate: